name: Deploy static site to Cloudflare Pages on Tag

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_PROJECT_NAME: github-action-tag
          GITHUB_TAG: ${{ github.ref_name }}
        run: |
          npx wrangler pages deploy ./public \
            --project-name $CLOUDFLARE_PROJECT_NAME \
            --branch $GITHUB_TAG \
            --account-id $CLOUDFLARE_ACCOUNT_ID \
            --api-token $CLOUDFLARE_API_TOKEN
